### ISSUE TITLE
sledovani v zahranici

### ISSUE THREAD

**Issue by mailyspamy** [kodi-czsk/plugin.video.teevee.sk#4]
Ahoj topserialy podminuji sledovani v zahranici prihlasenim se. Ucet tam jiz mam ale v pluginu do kodi neni mozne zadat login a heslo. Mohl by jsi implementovat i moznost prihlaseni?

**Comment by lubo** [comment]
Ahoj, pre topserialy existuje [samostatny plugin](https://github.com/jose1711/plugin.video.topserialy.sk).
